# Generated by Django 5.0.3 on 2024-05-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_conversationuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="slug",
        ),
    ]
