# Generated by Django 5.0.3 on 2024-04-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Museum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Аббревиатура"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Музей",
                "verbose_name_plural": "Музеи",
            },
        ),
        migrations.CreateModel(
            name="MuseumUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Присоеденился"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        default="Сотрудник", max_length=30, verbose_name="Должность"
                    ),
                ),
                (
                    "access_level",
                    models.IntegerField(
                        choices=[
                            (0, "Employee"),
                            (1, "Manager"),
                            (2, "Moderator"),
                            (3, "Administrator"),
                            (4, "Owner"),
                        ],
                        default=0,
                        verbose_name="Уровень доступа",
                    ),
                ),
                (
                    "museum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="museum.museum",
                        verbose_name="Музей",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник музея",
                "verbose_name_plural": "Сотрудники музеев",
                "unique_together": {("user", "museum")},
            },
        ),
    ]
