# Generated by Django 5.0.3 on 2024-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="museumuser",
            name="access_level",
        ),
        migrations.AddField(
            model_name="museum",
            name="image_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_add_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_change_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_change_description",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_change_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_change_short_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_change_user_permissions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="can_delete_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="museumuser",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
