# Generated by Django 5.0.3 on 2024-05-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_alter_collectionitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"verbose_name": "Коллекция", "verbose_name_plural": "Коллекции"},
        ),
        migrations.AlterModelOptions(
            name="usercollection",
            options={
                "verbose_name": "Коллекция пользователей",
                "verbose_name_plural": "Коллекции пользователей",
            },
        ),
    ]
